services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev.api
    ports:
      - "4000:4000"
    volumes:
      - /app/apps/api/node_modules
    develop:
      watch:
        - action: sync
          path: ./apps/api
          target: /app/apps/api
          ignore:
            - node_modules/
        - action: rebuild
          path: apps/api/package.json
    env_file:
      - apps/api/.env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: npm run start:dev
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev.web
    ports:
      - "3000:3000"
    volumes:
      - /app/apps/web/node_modules
    develop:
      watch:
        - action: sync
          path: ./apps/web
          target: /app/apps/web
          ignore:
            - node_modules/
        - action: rebuild
          path: apps/web/package.json
    env_file:
      - apps/web/.env
    environment:
      - INTERNAL_USERS_URL=http://api:4000/api/users
      - INTERNAL_BACKEND_URL=http://api:4000
      - WATCHPACK_POLLING=true
    command: npm run dev
    depends_on:
      - api

  db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=people-orbit-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
