services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev.api
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/web/node_modules
    env_file:
      - apps/api/.env
    environment:
      - NODE_ENV=development
    command: npm run dev:api

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile.dev.web
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/web/node_modules
    env_file:
      - apps/web/.env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NODE_ENV=development
    command: npm run dev:web
    depends_on:
      - api
