import { Person } from "./types/Person";

export const dummyPersonData: Person[] = [
  {
    id: 1,
    firstName: "Arjun",
    lastName: "Mehta",
    designation: "Senior Software Engineer",
    email: "arjun.mehta@examplesoft.com",
    phone: "+91 98765 43210",
    profilePic: "https://i.pravatar.cc/300?u=1",
    bgImage: "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
    bio: "Full-stack wizard with a love for distributed systems and filter coffee.",
    skills: ["React", "Node.js", "Kubernetes"],
    socialLinks: { linkedIn: "https://linkedin.com/in/arjunmehta", github: "https://github.com/arjunm" }
  },
  {
    id: 2,
    firstName: "Priya",
    lastName: "Sharma",
    designation: "Product Designer",
    email: "priya.sharma@examplesoft.com",
    phone: "+91 91234 56789",
    profilePic: "https://i.pravatar.cc/300?u=2",
    bgImage: "https://images.unsplash.com/photo-1558655146-d09347e92766",
    bio: "Crafting pixel-perfect experiences. Obsessed with typography and user empathy.",
    skills: ["Figma", "Adobe XD", "Tailwind CSS"],
    socialLinks: { linkedIn: "https://linkedin.com/in/psharma", website: "https://priyasharma.design" }
  },
  {
    id: 3,
    firstName: "Rohan",
    lastName: "Gupta",
    designation: "DevOps Lead",
    email: "rohan.gupta@examplesoft.com",
    phone: "+91 99887 76655",
    profilePic: "https://i.pravatar.cc/300?u=3",
    bgImage: "https://images.unsplash.com/photo-1618401471353-b98aadebc248",
    bio: "Automating everything that can be automated. Cloud native enthusiast.",
    skills: ["AWS", "Terraform", "Docker"],
    socialLinks: { github: "https://github.com/rohan-devops" }
  },
  {
    id: 4,
    firstName: "Ananya",
    lastName: "Iyer",
    designation: "Frontend Architect",
    email: "ananya.iyer@examplesoft.com",
    phone: "+91 98220 11223",
    profilePic: "https://i.pravatar.cc/300?u=4",
    bgImage: "https://images.unsplash.com/photo-1550745165-9bc0b252726f",
    bio: "Building the next generation of web interfaces with Next.js and WebGL.",
    skills: ["TypeScript", "Three.js", "Next.js"],
    socialLinks: { linkedIn: "https://linkedin.com/in/ananyaiyer" }
  },
  {
    id: 5,
    firstName: "Vikram",
    lastName: "Singh",
    designation: "Backend Engineer",
    email: "vikram.singh@examplesoft.com",
    phone: "+91 97654 32109",
    profilePic: "https://i.pravatar.cc/300?u=5",
    bgImage: "https://images.unsplash.com/photo-1555066931-4365d14bab8c",
    bio: "Java and NestJS expert. I enjoy optimizing SQL queries for fun.",
    skills: ["NestJS", "PostgreSQL", "Redis"],
    socialLinks: { github: "https://github.com/vikram-s" }
  },
  {
    id: 6,
    firstName: "Ishita",
    lastName: "Verma",
    designation: "QA Automation Engineer",
    email: "ishita.verma@examplesoft.com",
    phone: "+91 96543 21098",
    profilePic: "https://i.pravatar.cc/300?u=6",
    bgImage: "https://images.unsplash.com/photo-1510511459019-5dee997d7db4",
    bio: "Breaking code so you don't have to. Cypress and Playwright expert.",
    skills: ["Cypress", "Selenium", "Jest"],
    socialLinks: { linkedIn: "https://linkedin.com/in/ishitaverma" }
  },
  {
    id: 7,
    firstName: "Siddharth",
    lastName: "Malhotra",
    designation: "Engineering Manager",
    email: "siddharth.malhotra@examplesoft.com",
    phone: "+91 95432 10987",
    profilePic: "https://i.pravatar.cc/300?u=7",
    bgImage: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
    bio: "Leading teams to build impactful products. Advocate for agile and mental health.",
    skills: ["Leadership", "Agile", "Strategy"],
    socialLinks: { linkedIn: "https://linkedin.com/in/sidmalhotra" }
  },
  {
    id: 8,
    firstName: "Kavya",
    lastName: "Reddy",
    designation: "Mobile App Developer",
    email: "kavya.reddy@examplesoft.com",
    phone: "+91 94321 09876",
    profilePic: "https://i.pravatar.cc/300?u=8",
    bgImage: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c",
    bio: "React Native enthusiast. Building seamless cross-platform experiences.",
    skills: ["React Native", "Swift", "Kotlin"],
    socialLinks: { github: "https://github.com/kavyareddy" }
  },
  {
    id: 9,
    firstName: "Aditya",
    lastName: "Chopra",
    designation: "Data Scientist",
    email: "aditya.chopra@examplesoft.com",
    phone: "+91 93210 98765",
    profilePic: "https://i.pravatar.cc/300?u=9",
    bgImage: "https://images.unsplash.com/photo-1551288049-bbbda536339a",
    bio: "Finding patterns in chaos. Python, PyTorch, and a bit of magic.",
    skills: ["Python", "PyTorch", "Pandas"],
    socialLinks: { website: "https://adityachopra.ai" }
  },
  {
    id: 10,
    firstName: "Sana",
    lastName: "Khan",
    designation: "UX Researcher",
    email: "sana.khan@examplesoft.com",
    phone: "+91 92109 87654",
    profilePic: "https://i.pravatar.cc/300?u=10",
    bgImage: "https://images.unsplash.com/photo-1531403009284-440f080d1e12",
    bio: "Understanding why users do what they do. Research is my superpower.",
    skills: ["User Interviews", "Hotjar", "Usability Testing"],
    socialLinks: { linkedIn: "https://linkedin.com/in/sanakhan" }
  },
  {
    id: 11,
    firstName: "Rahul",
    lastName: "Deshmukh",
    designation: "Security Analyst",
    email: "rahul.deshmukh@examplesoft.com",
    phone: "+91 91098 76543",
    profilePic: "https://i.pravatar.cc/300?u=11",
    bgImage: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b",
    bio: "Securing the perimeter. Ethical hacker by day, gamer by night.",
    skills: ["Penetration Testing", "OAuth", "WAF"],
    socialLinks: { github: "https://github.com/rahulsec" }
  },
  {
    id: 12,
    firstName: "Meera",
    lastName: "Nair",
    designation: "Technical Writer",
    email: "meera.nair@examplesoft.com",
    phone: "+91 90987 65432",
    profilePic: "https://i.pravatar.cc/300?u=12",
    bgImage: "https://images.unsplash.com/photo-1455390582262-044cdead277a",
    bio: "Translating complex code into human-readable documentation.",
    skills: ["Markdown", "Docusaurus", "Technical Writing"],
    socialLinks: { linkedIn: "https://linkedin.com/in/meeranair" }
  }
];