import { People } from './types/people.type';

export const dummyData: People[] = [
  {
    id: 1,
    firstName: 'Arjun',
    lastName: 'Mehta',
    age: 32,
    designation: 'Senior Software Engineer',
    email: 'arjun.mehta@examplesoft.com',
    phone: '+91 98765 43210',
    profilePic: 'https://i.pravatar.cc/300?u=1',
    bgImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085',
    bio: 'Full-stack wizard with a love for distributed systems and filter coffee.',
    skills: ['React', 'Node.js', 'Kubernetes'],
    socialLinks: {
      linkedIn: 'https://linkedin.com/in/arjunmehta',
      github: 'https://github.com/arjunm',
    },
    createdOn: new Date(),
  },
  {
    id: 2,
    firstName: 'Priya',
    lastName: 'Sharma',
    age: 28,
    designation: 'Product Designer',
    email: 'priya.sharma@examplesoft.com',
    phone: '+91 91234 56789',
    profilePic: 'https://i.pravatar.cc/300?u=2',
    bgImage: 'https://images.unsplash.com/photo-1558655146-d09347e92766',
    bio: 'Crafting pixel-perfect experiences. Obsessed with typography and user empathy.',
    skills: ['Figma', 'Adobe XD', 'Tailwind CSS'],
    socialLinks: {
      linkedIn: 'https://linkedin.com/in/psharma',
      website: 'https://priyasharma.design',
    },
    createdOn: new Date(),
  },
  {
    id: 3,
    firstName: 'Rohan',
    lastName: 'Gupta',
    age: 35,
    designation: 'DevOps Lead',
    email: 'rohan.gupta@examplesoft.com',
    phone: '+91 99887 76655',
    profilePic: 'https://i.pravatar.cc/300?u=3',
    bgImage: 'https://images.unsplash.com/photo-1618401471353-b98aadebc248',
    bio: 'Automating everything that can be automated. Cloud native enthusiast.',
    skills: ['AWS', 'Terraform', 'Docker'],
    socialLinks: { github: 'https://github.com/rohan-devops' },
    createdOn: new Date(),
  },
  {
    id: 4,
    firstName: 'Ananya',
    lastName: 'Iyer',
    age: 30,
    designation: 'Frontend Architect',
    email: 'ananya.iyer@examplesoft.com',
    phone: '+91 98220 11223',
    profilePic: 'https://i.pravatar.cc/300?u=4',
    bgImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f',
    bio: 'Building the next generation of web interfaces with Next.js and WebGL.',
    skills: ['TypeScript', 'Three.js', 'Next.js'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/ananyaiyer' },
    createdOn: new Date(),
  },
  {
    id: 5,
    firstName: 'Vikram',
    lastName: 'Singh',
    age: 29,
    designation: 'Backend Engineer',
    email: 'vikram.singh@examplesoft.com',
    phone: '+91 97654 32109',
    profilePic: 'https://i.pravatar.cc/300?u=5',
    bgImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c',
    bio: 'Java and NestJS expert. I enjoy optimizing SQL queries for fun.',
    skills: ['NestJS', 'PostgreSQL', 'Redis'],
    socialLinks: { github: 'https://github.com/vikram-s' },
    createdOn: new Date(),
  },
  {
    id: 6,
    firstName: 'Ishita',
    lastName: 'Verma',
    age: 27,
    designation: 'QA Automation Engineer',
    email: 'ishita.verma@examplesoft.com',
    phone: '+91 96543 21098',
    profilePic: 'https://i.pravatar.cc/300?u=6',
    bgImage: 'https://images.unsplash.com/photo-1510511459019-5dee997d7db4',
    bio: "Breaking code so you don't have to. Cypress and Playwright expert.",
    skills: ['Cypress', 'Selenium', 'Jest'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/ishitaverma' },
    createdOn: new Date(),
  },
  {
    id: 7,
    firstName: 'Siddharth',
    lastName: 'Malhotra',
    age: 42,
    designation: 'Engineering Manager',
    email: 'siddharth.malhotra@examplesoft.com',
    phone: '+91 95432 10987',
    profilePic: 'https://i.pravatar.cc/300?u=7',
    bgImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d',
    bio: 'Leading teams to build impactful products. Advocate for agile and mental health.',
    skills: ['Leadership', 'Agile', 'Strategy'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/sidmalhotra' },
    createdOn: new Date(),
  },
  {
    id: 8,
    firstName: 'Kavya',
    lastName: 'Reddy',
    age: 26,
    designation: 'Mobile App Developer',
    email: 'kavya.reddy@examplesoft.com',
    phone: '+91 94321 09876',
    profilePic: 'https://i.pravatar.cc/300?u=8',
    bgImage: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c',
    bio: 'React Native enthusiast. Building seamless cross-platform experiences.',
    skills: ['React Native', 'Swift', 'Kotlin'],
    socialLinks: { github: 'https://github.com/kavyareddy' },
    createdOn: new Date(),
  },
  {
    id: 9,
    firstName: 'Aditya',
    lastName: 'Chopra',
    age: 31,
    designation: 'Data Scientist',
    email: 'aditya.chopra@examplesoft.com',
    phone: '+91 93210 98765',
    profilePic: 'https://i.pravatar.cc/300?u=9',
    bgImage: 'https://images.unsplash.com/photo-1551288049-bbbda536339a',
    bio: 'Finding patterns in chaos. Python, PyTorch, and a bit of magic.',
    skills: ['Python', 'PyTorch', 'Pandas'],
    socialLinks: { website: 'https://adityachopra.ai' },
    createdOn: new Date(),
  },
  {
    id: 10,
    firstName: 'Sana',
    lastName: 'Khan',
    age: 29,
    designation: 'UX Researcher',
    email: 'sana.khan@examplesoft.com',
    phone: '+91 92109 87654',
    profilePic: 'https://i.pravatar.cc/300?u=10',
    bgImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12',
    bio: 'Understanding why users do what they do. Research is my superpower.',
    skills: ['User Interviews', 'Hotjar', 'Usability Testing'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/sanakhan' },
    createdOn: new Date(),
  },
  {
    id: 11,
    firstName: 'Rahul',
    lastName: 'Deshmukh',
    age: 33,
    designation: 'Security Analyst',
    email: 'rahul.deshmukh@examplesoft.com',
    phone: '+91 91098 76543',
    profilePic: 'https://i.pravatar.cc/300?u=11',
    bgImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b',
    bio: 'Securing the perimeter. Ethical hacker by day, gamer by night.',
    skills: ['Penetration Testing', 'OAuth', 'WAF'],
    socialLinks: { github: 'https://github.com/rahulsec' },
    createdOn: new Date(),
  },
  {
    id: 12,
    firstName: 'Meera',
    lastName: 'Nair',
    age: 30,
    designation: 'Technical Writer',
    email: 'meera.nair@examplesoft.com',
    phone: '+91 90987 65432',
    profilePic: 'https://i.pravatar.cc/300?u=12',
    bgImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a',
    bio: 'Translating complex code into human-readable documentation.',
    skills: ['Markdown', 'Docusaurus', 'Technical Writing'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/meeranair' },
    createdOn: new Date(),
  },
  {
    id: 13,
    firstName: 'Zoya',
    lastName: 'Ansari',
    age: 27,
    designation: 'UI Developer',
    email: 'zoya.ansari@examplesoft.com',
    phone: '+91 89876 54321',
    profilePic: 'https://i.pravatar.cc/300?u=13',
    bgImage: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8',
    bio: 'Turning Figma dreams into CSS reality. Animation enthusiast.',
    skills: ['SASS', 'Framer Motion', 'GSAP'],
    socialLinks: { github: 'https://github.com/zoya-ui' },
    createdOn: new Date(),
  },
  {
    id: 14,
    firstName: 'Kabir',
    lastName: 'Bahl',
    age: 34,
    designation: 'Site Reliability Engineer',
    email: 'kabir.bahl@examplesoft.com',
    phone: '+91 88765 43210',
    profilePic: 'https://i.pravatar.cc/300?u=14',
    bgImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa',
    bio: 'Maintaining 99.99% uptime while drinking 100% Arabica coffee.',
    skills: ['Prometheus', 'Grafana', 'Go'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/kabirbahl' },
    createdOn: new Date(),
  },
  {
    id: 15,
    firstName: 'Tara',
    lastName: 'Kapoor',
    age: 31,
    designation: 'ML Engineer',
    email: 'tara.kapoor@examplesoft.com',
    phone: '+91 87654 32109',
    profilePic: 'https://i.pravatar.cc/300?u=15',
    bgImage: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8',
    bio: 'Training models to understand the world, one epoch at a time.',
    skills: ['TensorFlow', 'Scikit-learn', 'KServe'],
    socialLinks: { website: 'https://tara-ml.io' },
    createdOn: new Date(),
  },
  {
    id: 16,
    firstName: 'Aryan',
    lastName: 'Malik',
    age: 25,
    designation: 'Junior Frontend Developer',
    email: 'aryan.malik@examplesoft.com',
    phone: '+91 86543 21098',
    profilePic: 'https://i.pravatar.cc/300?u=16',
    bgImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97',
    bio: 'Fresh out of bootcamp and ready to push to production (carefully).',
    skills: ['JavaScript', 'HTML5', 'CSS3'],
    socialLinks: { github: 'https://github.com/aryan-dev' },
    createdOn: new Date(),
  },
  {
    id: 17,
    firstName: 'Nandini',
    lastName: 'Rao',
    age: 33,
    designation: 'Data Architect',
    email: 'nandini.rao@examplesoft.com',
    phone: '+91 85432 10987',
    profilePic: 'https://i.pravatar.cc/300?u=17',
    bgImage: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d',
    bio: 'Designing scalable data schemas for complex enterprise needs.',
    skills: ['Snowflake', 'BigQuery', 'dbt'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/nandinirao' },
    createdOn: new Date(),
  },
  {
    id: 18,
    firstName: 'Sameer',
    lastName: 'Joshi',
    age: 38,
    designation: 'Solutions Architect',
    email: 'sameer.joshi@examplesoft.com',
    phone: '+91 84321 09876',
    profilePic: 'https://i.pravatar.cc/300?u=18',
    bgImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f',
    bio: 'Connecting business requirements with robust technical blueprints.',
    skills: ['Azure', 'Microservices', 'Kafka'],
    socialLinks: { website: 'https://joshi-architect.com' },
    createdOn: new Date(),
  },
  {
    id: 19,
    firstName: 'Riya',
    lastName: 'Sen',
    age: 26,
    designation: 'Cloud Engineer',
    email: 'riya.sen@examplesoft.com',
    phone: '+91 83210 98765',
    profilePic: 'https://i.pravatar.cc/300?u=19',
    bgImage: 'https://images.unsplash.com/photo-1484417894907-623942c8ee29',
    bio: "The cloud is just someone else's computer, and I manage it.",
    skills: ['GCP', 'CloudFormation', 'Python'],
    socialLinks: { github: 'https://github.com/riya-cloud' },
    createdOn: new Date(),
  },
  {
    id: 20,
    firstName: 'Arnav',
    lastName: 'Goel',
    age: 29,
    designation: 'Android Developer',
    email: 'arnav.goel@examplesoft.com',
    phone: '+91 82109 87654',
    profilePic: 'https://i.pravatar.cc/300?u=20',
    bgImage: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9',
    bio: 'Native Android purist. Living the life of Jetpack Compose.',
    skills: ['Kotlin', 'Coroutines', 'Retrofit'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/arnavandroid' },
    createdOn: new Date(),
  },
  {
    id: 21,
    firstName: 'Kriti',
    lastName: 'Pandey',
    age: 30,
    designation: 'Full Stack Engineer',
    email: 'kriti.pandey@examplesoft.com',
    phone: '+91 81098 76543',
    profilePic: 'https://i.pravatar.cc/300?u=21',
    bgImage: 'https://images.unsplash.com/photo-1587620962725-abab7fe55159',
    bio: 'From the database to the DOM, I build it all.',
    skills: ['Vue.js', 'Express', 'MongoDB'],
    socialLinks: { github: 'https://github.com/kriti-codes' },
    createdOn: new Date(),
  },
  {
    id: 22,
    firstName: 'Dev',
    lastName: 'Patel',
    age: 36,
    designation: 'Security Engineer',
    email: 'dev.patel@examplesoft.com',
    phone: '+91 80987 65432',
    profilePic: 'https://i.pravatar.cc/300?u=22',
    bgImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc51',
    bio: 'Encryption is the name of the game. Zero trust advocate.',
    skills: ['IAM', 'VPC Security', 'Burp Suite'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/devsecurity' },
    createdOn: new Date(),
  },
  {
    id: 23,
    firstName: 'Anjali',
    lastName: 'Bose',
    age: 32,
    designation: 'Product Manager',
    email: 'anjali.bose@examplesoft.com',
    phone: '+91 79876 54321',
    profilePic: 'https://i.pravatar.cc/300?u=23',
    bgImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f',
    bio: 'Bridging the gap between users and engineers.',
    skills: ['Jira', 'Roadmapping', 'User Feedback'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/anjalibose' },
    createdOn: new Date(),
  },
  {
    id: 24,
    firstName: 'Varun',
    lastName: 'Mehra',
    age: 28,
    designation: 'Blockchain Developer',
    email: 'varun.mehra@examplesoft.com',
    phone: '+91 78765 43210',
    profilePic: 'https://i.pravatar.cc/300?u=24',
    bgImage: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0',
    bio: 'Decentralizing the future with Solidity and smart contracts.',
    skills: ['Solidity', 'Web3.js', 'Ethereum'],
    socialLinks: { github: 'https://github.com/varun-crypto' },
    createdOn: new Date(),
  },
  {
    id: 25,
    firstName: 'Nikita',
    lastName: 'Kaur',
    age: 27,
    designation: 'Data Analyst',
    email: 'nikita.kaur@examplesoft.com',
    phone: '+91 77654 32109',
    profilePic: 'https://i.pravatar.cc/300?u=25',
    bgImage: 'https://images.unsplash.com/photo-1551288049-bbbda536339a',
    bio: 'Visualizing stories hidden in the noise of big data.',
    skills: ['Tableau', 'SQL', 'Power BI'],
    socialLinks: { website: 'https://nikita-data.com' },
    createdOn: new Date(),
  },
  {
    id: 26,
    firstName: 'Rishabh',
    lastName: 'Tiwari',
    age: 31,
    designation: 'iOS Developer',
    email: 'rishabh.tiwari@examplesoft.com',
    phone: '+91 76543 21098',
    profilePic: 'https://i.pravatar.cc/300?u=26',
    bgImage: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c',
    bio: 'Lover of Swift, SwiftUI, and Apple ecosystem aesthetics.',
    skills: ['SwiftUI', 'CoreData', 'Combine'],
    socialLinks: { github: 'https://github.com/rishabh-ios' },
    createdOn: new Date(),
  },
  {
    id: 27,
    firstName: 'Amrita',
    lastName: 'Das',
    age: 29,
    designation: 'Content Designer',
    email: 'amrita.das@examplesoft.com',
    phone: '+91 75432 10987',
    profilePic: 'https://i.pravatar.cc/300?u=27',
    bgImage: 'https://images.unsplash.com/photo-1455390582262-044cdead277a',
    bio: 'Words are UI too. Helping products speak clearly.',
    skills: ['UX Writing', 'Content Strategy', 'Copywriting'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/amritadas' },
    createdOn: new Date(),
  },
  {
    id: 28,
    firstName: 'Tushar',
    lastName: 'Sane',
    age: 30,
    designation: 'DevOps Engineer',
    email: 'tushar.sane@examplesoft.com',
    phone: '+91 74321 09876',
    profilePic: 'https://i.pravatar.cc/300?u=28',
    bgImage: 'https://images.unsplash.com/photo-1618401471353-b98aadebc248',
    bio: "If it's not in Git, it doesn't exist. Jenkins lover.",
    skills: ['Jenkins', 'Ansible', 'Bash'],
    socialLinks: { github: 'https://github.com/tushar-ops' },
    createdOn: new Date(),
  },
  {
    id: 29,
    firstName: 'Sneha',
    lastName: 'Kulkarni',
    age: 35,
    designation: 'QA Lead',
    email: 'sneha.kulkarni@examplesoft.com',
    phone: '+91 73210 98765',
    profilePic: 'https://i.pravatar.cc/300?u=29',
    bgImage: 'https://images.unsplash.com/photo-1510511459019-5dee997d7db4',
    bio: 'Ensuring quality at scale. Manager of bugs and people.',
    skills: ['TestRail', 'JMeter', 'Team Leadership'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/snehakulkarni' },
    createdOn: new Date(),
  },
  {
    id: 30,
    firstName: 'Manish',
    lastName: 'Yadav',
    age: 33,
    designation: 'Database Administrator',
    email: 'manish.yadav@examplesoft.com',
    phone: '+91 72109 87654',
    profilePic: 'https://i.pravatar.cc/300?u=30',
    bgImage: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d',
    bio: 'Guardian of the data. Master of performance tuning.',
    skills: ['Oracle', 'MySQL', 'Query Optimization'],
    socialLinks: { github: 'https://github.com/manish-db' },
    createdOn: new Date(),
  },
  {
    id: 31,
    firstName: 'Pooja',
    lastName: 'Bhatia',
    age: 26,
    designation: 'Frontend Developer',
    email: 'pooja.bhatia@examplesoft.com',
    phone: '+91 71098 76543',
    profilePic: 'https://i.pravatar.cc/300?u=31',
    bgImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f',
    bio: 'Creating interactive interfaces with React and Redux.',
    skills: ['React', 'Redux', 'Material UI'],
    socialLinks: { github: 'https://github.com/pooja-b' },
    createdOn: new Date(),
  },
  {
    id: 32,
    firstName: 'Kunwar',
    lastName: 'Singh',
    age: 40,
    designation: 'CTO',
    email: 'kunwar.singh@examplesoft.com',
    phone: '+91 70987 65432',
    profilePic: 'https://i.pravatar.cc/300?u=32',
    bgImage: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d',
    bio: 'Defining the technology vision for the next decade.',
    skills: ['Innovation', 'Architecture', 'Public Speaking'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/kunwarsingh' },
    createdOn: new Date(),
  },
  {
    id: 33,
    firstName: 'Isha',
    lastName: 'Nambiar',
    age: 24,
    designation: 'Intern Engineer',
    email: 'isha.nambiar@examplesoft.com',
    phone: '+91 69876 54321',
    profilePic: 'https://i.pravatar.cc/300?u=33',
    bgImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3',
    bio: 'Learning the ropes and coding until 3 AM.',
    skills: ['Python', 'C++', 'Algorithms'],
    socialLinks: { github: 'https://github.com/isha-n' },
    createdOn: new Date(),
  },
  {
    id: 34,
    firstName: 'Yash',
    lastName: 'Vardhan',
    age: 31,
    designation: 'Systems Engineer',
    email: 'yash.vardhan@examplesoft.com',
    phone: '+91 68765 43210',
    profilePic: 'https://i.pravatar.cc/300?u=34',
    bgImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc51',
    bio: 'Linux lover and shell scripting pro.',
    skills: ['Linux', 'Shell', 'Nginx'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/yashv' },
    createdOn: new Date(),
  },
  {
    id: 35,
    firstName: 'Diya',
    lastName: 'Menon',
    age: 28,
    designation: 'Marketing Technologist',
    email: 'diya.menon@examplesoft.com',
    phone: '+91 67654 32109',
    profilePic: 'https://i.pravatar.cc/300?u=35',
    bgImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f',
    bio: 'Integrating tech stack for high-performance marketing.',
    skills: ['Hubspot', 'Segment', 'Analytics'],
    socialLinks: { website: 'https://diya.marketing' },
    createdOn: new Date(),
  },
  {
    id: 36,
    firstName: 'Pranav',
    lastName: 'Ramesh',
    age: 34,
    designation: 'MLOps Engineer',
    email: 'pranav.ramesh@examplesoft.com',
    phone: '+91 66543 21098',
    profilePic: 'https://i.pravatar.cc/300?u=36',
    bgImage: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8',
    bio: 'Bridging the gap between ML models and production.',
    skills: ['Kubeflow', 'MLflow', 'Docker'],
    socialLinks: { github: 'https://github.com/pranav-ml' },
    createdOn: new Date(),
  },
  {
    id: 37,
    firstName: 'Avni',
    lastName: 'Sarin',
    age: 27,
    designation: 'Visual Designer',
    email: 'avni.sarin@examplesoft.com',
    phone: '+91 65432 10987',
    profilePic: 'https://i.pravatar.cc/300?u=37',
    bgImage: 'https://images.unsplash.com/photo-1558655146-d09347e92766',
    bio: 'Creating the visual identity of ExampleSoft.',
    skills: ['Illustrator', 'Photoshop', 'Branding'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/avnisarin' },
    createdOn: new Date(),
  },
  {
    id: 38,
    firstName: 'Zaid',
    lastName: 'Hussain',
    age: 32,
    designation: 'Security Consultant',
    email: 'zaid.hussain@examplesoft.com',
    phone: '+91 64321 09876',
    profilePic: 'https://i.pravatar.cc/300?u=38',
    bgImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b',
    bio: 'Helping companies fix vulnerabilities before hackers find them.',
    skills: ['Ethical Hacking', 'Compliance', 'Audit'],
    socialLinks: { github: 'https://github.com/zaidsec' },
    createdOn: new Date(),
  },
  {
    id: 39,
    firstName: 'Tanvi',
    lastName: 'Mittal',
    age: 29,
    designation: 'HR Tech Manager',
    email: 'tanvi.mittal@examplesoft.com',
    phone: '+91 63210 98765',
    profilePic: 'https://i.pravatar.cc/300?u=39',
    bgImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f',
    bio: 'Optimizing employee experience through software.',
    skills: ['BambooHR', 'CultureAmp', 'Communication'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/tanvim' },
    createdOn: new Date(),
  },
  {
    id: 40,
    firstName: 'Kabir',
    lastName: 'Walia',
    age: 31,
    designation: 'Platform Engineer',
    email: 'kabir.walia@examplesoft.com',
    phone: '+91 62109 87654',
    profilePic: 'https://i.pravatar.cc/300?u=40',
    bgImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa',
    bio: 'Building the foundation for developer productivity.',
    skills: ['K8s', 'Helm', 'Terraform'],
    socialLinks: { github: 'https://github.com/kabir-plat' },
    createdOn: new Date(),
  },
  {
    id: 41,
    firstName: 'Bhavna',
    lastName: 'Grover',
    age: 30,
    designation: 'Growth Engineer',
    email: 'bhavna.grover@examplesoft.com',
    phone: '+91 61098 76543',
    profilePic: 'https://i.pravatar.cc/300?u=41',
    bgImage: 'https://images.unsplash.com/photo-1484417894907-623942c8ee29',
    bio: 'A/B testing my way to higher conversion rates.',
    skills: ['Amplitude', 'Optimizely', 'Node.js'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/bhavnag' },
    createdOn: new Date(),
  },
  {
    id: 42,
    firstName: 'Sameer',
    lastName: 'Khan',
    age: 33,
    designation: 'Release Manager',
    email: 'sameer.k@examplesoft.com',
    phone: '+91 60987 65432',
    profilePic: 'https://i.pravatar.cc/300?u=42',
    bgImage: 'https://images.unsplash.com/photo-1618401471353-b98aadebc248',
    bio: 'Ensuring smooth deployments on every release Tuesday.',
    skills: ['CI/CD', 'GitLab', 'Planning'],
    socialLinks: { github: 'https://github.com/skhan-rel' },
    createdOn: new Date(),
  },
  {
    id: 43,
    firstName: 'Mehak',
    lastName: 'Suri',
    age: 26,
    designation: 'Interaction Designer',
    email: 'mehak.suri@examplesoft.com',
    phone: '+91 59876 54321',
    profilePic: 'https://i.pravatar.cc/300?u=43',
    bgImage: 'https://images.unsplash.com/photo-1558655146-d09347e92766',
    bio: 'Animating the micro-interactions that delight users.',
    skills: ['After Effects', 'Lottie', 'Principle'],
    socialLinks: { website: 'https://mehak.design' },
    createdOn: new Date(),
  },
  {
    id: 44,
    firstName: 'Arjun',
    lastName: 'Bakshi',
    age: 37,
    designation: 'Staff Engineer',
    email: 'arjun.b@examplesoft.com',
    phone: '+91 58765 43210',
    profilePic: 'https://i.pravatar.cc/300?u=44',
    bgImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085',
    bio: 'Solving the hardest technical problems in the company.',
    skills: ['System Design', 'Rust', 'Mentorship'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/arjunbakshi' },
    createdOn: new Date(),
  },
  {
    id: 45,
    firstName: 'Leila',
    lastName: 'Fernandes',
    age: 28,
    designation: 'Accessibility Specialist',
    email: 'leila.f@examplesoft.com',
    phone: '+91 57654 32109',
    profilePic: 'https://i.pravatar.cc/300?u=45',
    bgImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3',
    bio: 'Making the web usable for everyone, regardless of ability.',
    skills: ['WCAG', 'ARIA', 'Screen Readers'],
    socialLinks: { github: 'https://github.com/leila-a11y' },
    createdOn: new Date(),
  },
  {
    id: 46,
    firstName: 'Neil',
    lastName: 'Choudhury',
    age: 31,
    designation: 'Data Engineer',
    email: 'neil.c@examplesoft.com',
    phone: '+91 56543 21098',
    profilePic: 'https://i.pravatar.cc/300?u=46',
    bgImage: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d',
    bio: 'Pipelines, ETL, and lots of Spark.',
    skills: ['Airflow', 'Spark', 'Hadoop'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/neilchoudhury' },
    createdOn: new Date(),
  },
  {
    id: 47,
    firstName: 'Simran',
    lastName: 'Kaur',
    age: 29,
    designation: 'Customer Success Engineer',
    email: 'simran.k@examplesoft.com',
    phone: '+91 55432 10987',
    profilePic: 'https://i.pravatar.cc/300?u=47',
    bgImage: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12',
    bio: 'Solving technical issues and keeping our clients happy.',
    skills: ['Zendesk', 'SQL', 'Debugging'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/simrank' },
    createdOn: new Date(),
  },
  {
    id: 48,
    firstName: 'Rohan',
    lastName: 'Dutta',
    age: 32,
    designation: 'Performance Engineer',
    email: 'rohan.d@examplesoft.com',
    phone: '+91 54321 09876',
    profilePic: 'https://i.pravatar.cc/300?u=48',
    bgImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c',
    bio: 'Shaving milliseconds off page loads.',
    skills: ['Lighthouse', 'Web Vitals', 'Caching'],
    socialLinks: { github: 'https://github.com/rohan-perf' },
    createdOn: new Date(),
  },
  {
    id: 49,
    firstName: 'Kiara',
    lastName: 'Advani',
    age: 27,
    designation: 'Scrum Master',
    email: 'kiara.a@examplesoft.com',
    phone: '+91 53210 98765',
    profilePic: 'https://i.pravatar.cc/300?u=49',
    bgImage: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f',
    bio: 'Facilitating teams to achieve their best sprint ever.',
    skills: ['Scrum', 'Kanban', 'Facilitation'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/kiaraa' },
    createdOn: new Date(),
  },
  {
    id: 50,
    firstName: 'Amit',
    lastName: 'Mishra',
    age: 35,
    designation: 'Infrastructure Manager',
    email: 'amit.m@examplesoft.com',
    phone: '+91 52109 87654',
    profilePic: 'https://i.pravatar.cc/300?u=50',
    bgImage: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc51',
    bio: 'Managing the physical and virtual hardware that runs it all.',
    skills: ['Data Centers', 'Networking', 'Security'],
    socialLinks: { linkedIn: 'https://linkedin.com/in/amitmishra' },
    createdOn: new Date(),
  },
];
